=== anoopkota/openhack-durable-entities/docs/json/schemas/input-onhand-schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "type": "object",
    "title": "OnHand Schema",
    "description": "The schema for products on hand.",
    "default": {},
    "additionalProperties": true,
    "required": ["id", "divisionId", "storeId", "upc", "inventoryCount", "productName", "lastUpdateTimestamp"],
    "properties": {
        "id": {
            "$id": "#/properties/id",
            "type": "string",
            "title": "The Cosmos DB document id",
            "description": "The format is divisionId:storeId:upc",
            "examples": ["div1:store005:0003400029005"]
        },
        "divisionId": {
            "$id": "#/properties/divisionId",
            "type": "string",
            "title": "The division id",
            "examples": ["div1"]
        },
        "storeId": {
            "$id": "#/properties/storeId",
            "type": "string",
            "title": "The store id",
            "examples": ["store005"]
        },
        "upc": {
            "$id": "#/properties/upc",
            "type": "string",
            "title": "The universal product code",
            "examples": ["0003400029005"]
        },
        "inventoryCount": {
            "$id": "#/properties/inventoryCount",
            "type": "integer",
            "title": "The current inventory of a given item",
            "examples": [1000]
        },
        "productName": {
            "$id": "#/properties/productName",
            "type": "string",
            "title": "The name of the product",
            "examples": ["HERSHEY'S Milk Chocolate Bars"]
        },
        "description": {
            "$id": "#/properties/description",
            "type": "string",
            "title": "The description of the product",
            "examples": ["HERSHEY'S Milk Chocolate Bars are the classic full size chocolate candy bars youâ€™ve always enjoyed!"]
        },
        "lastUpdateTimestamp": {
            "$id": "#/properties/lastUpdateTimestamp",
            "type": "string",
            "title": "The date and time of the last update",
            "description": "The format is yyyy-MM-dd HH:mm:ss and all dates should be in UTC",
            "examples": ["2020-05-13 9:00:00 AM"]
        }
    }
}

=== anoopkota/openhack-durable-entities/docs/json/samples/input-onhand-sample.json
{
    "id": "div1:store005:0003400029005",
    "divisionId": "div1",
    "storeId": "store005",
    "upc": "0003400029005",
    "inventoryCount": 1000,
    "productName": "HERSHEY'S Milk Chocolate Bars",
    "description": "HERSHEY'S Milk Chocolate Bars are the classic full size chocolate candy bars youâ€™ve always enjoyed!",
    "lastUpdateTimestamp": "2020-05-13 9:00:00 AM"
}
